### ISSUE TITLE
Apple trees give infinite apples

### ISSUE THREAD

**Issue by msgerbs** [SheepFighter/Stratus#14]
Simple enough. Do something to make it not unlimited free food.

**Comment by msgerbs** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Apple trees give unlimited apples](https://trello.com/c/rVYZnyqQ/6-apple-trees-give-unlimited-apples)

**Comment by SheepFighter** [comment]
This is incorrect. I coded it to yield ten apples, and I just tested it to be sure. It works. But if that's too many I'll happily change the amount.
